resolver: lts-14.27
local-bin-path: bin
extra-deps:
- hgmp-0.1.1
- long-double-0.1.1
- ref-fd-0.4.0.2
- rounded-1.1
- git: https://github.com/mainland/fixed-q.git
  commit: 2e7bfef593b1fc81179b0c4e414bf20cf552c676
- git: https://github.com/mainland/language-vhdl-quote.git
  commit: bdb5df7c609070da61cc417ca38f7d6a142e5355
- git: https://github.com/mainland/vhdl-codegen.git
  commit: b5e389eecadfa151b8245e065f9b9bae775d9508
