resolver: lts-14.27

packages:
- .

local-bin-path: bin

extra-deps:
- netlist-0.3.1
- netlist-to-vhdl-0.3.3
- sized-types-0.3.5.2
- data-reify-0.6
- git: https://github.com/ms4323/kansas-lava.git
  commit: 84bec0960fe0fcac32c6cda04f910f72a99490a2
